# Generated by Django 6.0.4 on 2026-04-19 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musicas', to='music.album'),
        ),
    ]
